jamesleoreyes/the-reyes-vault

client/package.json, server/nodemon.json, server/package.json, server/src/app.ts, server/src/config/app.ts, server/src/config/logger.ts, server/src/server.ts, server/src/utils/env.ts, server/tsconfig.json
This PR establishes the core server infrastructure and updates project dependencies to ensure optimal performance and development experience.
Server Infrastructure:
- Set up Express.js server with TypeScript support
- Implement environment variable configuration and validation
- Create custom colored logging system
- Configure development server using nodemon
- Establish basic Express app structure
Dependency Updates:
- Upgrade React and React DOM to v19.1.0
- Update development tools (ESLint, TypeScript, Vite)
- Enhance TypeScript configuration for server
- Reorganize server dependencies
- Standardize semicolon usage across server files
Technical Details:
- Added essential dependencies (express, dotenv)
- Implemented build script for server
- Configured TypeScript for both client and …
=> feat: Initialize Express server and update project dependencies

PLAN.md
Update PLAN.md to reflect completed initial setup tasks including:
- Next.js project initialization and structure
- Git/GitHub repository setup
- Supabase project creation and key configuration
- Cloudflare R2 bucket setup and configuration
- Vercel project connection and deployment verification
- Local environment setup (.env.local)
Remaining Phase 1 tasks include database schema design, environment variable configuration for production, and initial UI implementation.
=> docs(PLAN.md): Mark completed Phase 1 setup tasks

package.json
- Upgrade React and React DOM to version 19.1.0 for improved performance and features.
- Update TypeScript and related type definitions to ensure compatibility and enhance type safety.
- Adjust development dependencies for ESLint and Tailwind CSS to their latest versions for better tooling and styling capabilities.
=> chore: Update React and TypeScript dependencies in package.json

PLAN.md, package.json
- Upgrade React and React DOM to version 19.1.0 for improved performance and features.
- Update TypeScript and related type definitions to ensure compatibility and enhance type safety.
- Adjust development dependencies for ESLint and Tailwind CSS to their latest versions for better tooling and styling capabilities.
=> chore: Update React and TypeScript dependencies in package.json 

app/components/header-auth.tsx, app/components/submit-button.tsx, app/components/theme-switcher.tsx
- Add loading spinner and improved pending state to SubmitButton
- Update HeaderAuth to use enhanced SubmitButton for sign out
- Standardize button sizes and remove outline variants
- Add explicit cursor pointer states for interactive elements
=> feat(ui): Enhance button components with loading states and consistent styling

PLAN.md, README.md
This PR significantly enhances project documentation by:
1.  **Introducing a comprehensive `README.md`:**
*   Provides a clear project overview, including its purpose and goals.
*   Displays current MVP progress (23%) using a functional `geps.dev` progress bar.
*   Details core MVP features, the technology stack, and clear "Getting Started" instructions for local development.
*   Includes contribution guidelines and a link to the detailed `PLAN.md`.
2.  **Updating `PLAN.MD` for improved progress tracking:**
*   Marks recently completed sub-tasks within Phase 1 (Project Setup & Core Infrastructure), specifically related to UI integration, navigation, environment configuration, and TypeScript settings.
*   Adds individual `geps.dev` progress bar badges to each of the 8 development phases, …
=> docs: Enhance project documentation with README and detailed PLAN.md updates

PLAN.md
- Update section titles to remove numbering and enhance readability.
- Ensure uniformity in formatting across the document for better navigation.
=> docs: Revise section headings in PLAN.md for clarity and consistency

PLAN.md, README.md
- Update section titles to remove numbering and enhance readability.
- Ensure uniformity in formatting across the document for better navigation.
=> docs: Revise section headings in PLAN.md for clarity and consistency 

app/layout.tsx, package.json
Adds Vercel Analytics to the project for tracking and insights.
- Includes the `@vercel/analytics` package as a dependency.
- Integrates the `Analytics` component into the root layout.
=> feat: Integrate Vercel Analytics

app/layout.tsx
This PR enhances the application's SEO and social media sharing capabilities by implementing OpenGraph and Twitter Card metadata. It also improves code maintainability through metadata centralization.
Changes:
• Added Meta interface for type-safe metadata handling
• Created centralized meta object to manage shared metadata values
• Implemented OpenGraph metadata for better social media link previews
• Added Twitter Card metadata for improved Twitter sharing
• Refactored existing metadata to use centralized values
Technical Details:
- Introduced TypeScript interface for metadata type safety
- Centralized metadata values to reduce duplication and improve maintainability
- Added OpenGraph properties: type, title, siteName, description
- Added Twitter Card properties: title, description …
=> feat(meta): Enhance SEO with OpenGraph and Twitter Card Support

lib/authPaths.ts, utils/supabase/middleware.ts
This PR extracts authentication-related path constants into a dedicated file to improve maintainability and reduce duplication.
Changes:
- Created new lib/authPaths.ts to centralize path definitions used in auth flows
- Updated middleware.ts to use the new constants instead of hardcoded paths
- Grouped related paths into named exports for better organization and reusability
Benefits:
- Makes it easier to maintain and update auth-related paths across the application
- Reduces the risk of typos and inconsistencies
- Improves code readability and maintainability
- Enables better TypeScript support through centralized path definitions
=> refactor: extract auth path constants to improve maintainability

app/(auth-pages)/login/page.tsx, app/actions.ts, app/layout.tsx, components/login-form.tsx, components/ui/sonner.tsx, package.json
- Replace URL search params error handling with client-side toast notifications
- Add server action state management for better error handling
- Implement Sonner toast component for consistent notification UI
- Simplify login page component by removing search params logic
- Update action handlers to return structured error states
- Add type safety for action error states
- Fix password reset action redirects
=> refactor(auth): Improve login error handling with client-side toasts

app/(auth-pages)/login/page.tsx, app/(user)/dashboard/page.tsx, app/actions.ts, app/layout.tsx, components/login-form.tsx, components/ui/sonner.tsx, package.json
- Replace URL search params error handling with client-side toast notifications
- Add server action state management for better error handling
- Implement Sonner toast component for consistent notification UI
- Simplify login page component by removing search params logic
- Update action handlers to return structured error states
- Add type safety for action error states
- Fix password reset action redirects
=> refactor(auth): Improve login error handling with client-side toasts 

.hintrc, app/(auth-pages)/login/page.tsx, app/layout.tsx, app/manifest.ts, components/animate-ui/backgrounds/gradient.tsx, components/animate-ui/buttons/ripple.tsx, components/animate-ui/components/tooltip.tsx, components/login-form/anonymous-form.tsx, components/login-form/default-form.tsx, components/login-form/form.tsx, components/ui/sidebar.tsx, lib/config.ts, package.json
- Add animated UI components (gradient background, ripple button, tooltip)
- Redesign login page with gradient background and improved styling
- Refactor config management into centralized config object
- Update sidebar to use new animated tooltip component
- Improve form styling with better colors and shadows
- Add motion library for animations
- Configure webhint to allow inline styles
- Update manifest short name and add antialiased text
=> feat: Enhance UI with animated components and redesign login page

.hintrc, app/(auth-pages)/login/page.tsx, app/layout.tsx, app/manifest.ts, components/animate-ui/backgrounds/gradient.tsx, components/animate-ui/buttons/ripple.tsx, components/animate-ui/components/tooltip.tsx, components/login-form/anonymous-form.tsx, components/login-form/default-form.tsx, components/login-form/form.tsx, components/ui/sidebar.tsx, lib/config.ts, package.json
- Add animated UI components (gradient background, ripple button, tooltip)
- Redesign login page with gradient background and improved styling
- Refactor config management into centralized config object
- Update sidebar to use new animated tooltip component
- Improve form styling with better colors and shadows
- Add motion library for animations
- Configure webhint to allow inline styles
- Update manifest short name and add antialiased text
=> feat: Enhance UI with animated components and redesign login page 

README.md, app/layout.tsx, app/manifest.ts, components/animate-ui/backgrounds/gradient.tsx, components/login-form/anonymous-form.tsx, components/login-form/form.tsx, lib/config.ts, types/Config.ts, utils/supabase/admin.ts, utils/supabase/client.ts, utils/supabase/middleware.ts, utils/supabase/server.ts
This PR introduces a comprehensive restructuring of the application's configuration management system to improve type safety, maintainability, and developer experience.
**Configuration System Improvements:**
- Replaced single monolithic config object with modular, typed configuration exports
- Added TypeScript interfaces for app, URL, Supabase, and Cloudflare configurations
- Centralized all environment variable access through typed config modules
- Updated all component and utility imports to use the new configuration structure
- Enhanced type safety across the entire configuration management system
**Documentation Enhancements:**
- Added centered project logo to README for improved visual appeal
- Enhanced formatting and readability of project description
- Improved overall …
=> refactor: Restructure configuration system and enhance README documentation

README.md, app/layout.tsx
- Included a new startup image path in the metadata for improved branding on iOS devices.
- This change enhances the user experience by providing a visual identity during app launch.
=> feat: Add startup image to metadata in layout.tsx

README.md
- Included a new startup image path in the metadata for improved branding on iOS devices.
- This change enhances the user experience by providing a visual identity during app launch.
=> feat: Add startup image to metadata in layout.tsx 

src/app/(authenticated)/(user)/dashboard/page.tsx, src/app/(authenticated)/layout.tsx, src/components/demo-aware-nav.tsx, src/components/sidebar/app-sidebar.tsx, src/components/sidebar/sidebar-user.tsx, src/types/Config.ts, src/utils/demo.ts, src/utils/supabase/middleware.ts, src/utils/utils.ts
This PR further enhances the demo mode system to be more comprehensive and provide a safe, limited experience for anonymous users while maintaining full functionality for authenticated users.
- **Complete Admin Route Blocking**: All `/admin/*` routes are blocked at middleware level in demo mode
- **Fake User Data Generation**: Consistent, deterministic demo profiles based on user ID
- **Demo-Aware UI**: Components automatically hide admin features when in demo mode
- **Safe Environment**: Demo users cannot access or modify any admin functionality
- **Contextual Admin Access**: Moved admin button from sidebar to user dropdown menu
- **Role-Based Display**: Admin option only appears for users with admin role
- **Better UX**: Admin functionality is now grouped with other user-specific …
=> feat(demo): Implement comprehensive demo mode with admin restrictions and UI improvements

src/app/(authenticated)/(user)/dashboard/page.tsx, src/app/(authenticated)/layout.tsx, src/app/(authenticated)/memories/notes/page.tsx, src/components/sidebar/app-sidebar.tsx, src/components/sidebar/sidebar-user.tsx, src/components/ui/avatar.tsx, src/types/Profiles.ts, src/types/enums.ts, src/utils/demo.ts, src/utils/utils.ts
This PR transforms the application from using placeholder data to a fully personalized experience with real user information, enhanced demo mode, and improved overall UX.
- **Dynamic Sidebar**: Replaced hardcoded user data with actual profile information
- **Personalized Greetings**: Dashboard now shows "Hi, {first_name}!" instead of generic text
- **Real Names & Emails**: Sidebar displays actual user information from database
- **Avatar Initials**: Automatic fallback to user initials when no avatar is present
- **Severance-Themed Names**: Fun, memorable character names for demo users
- **Generated Avatars**: Automatic avatar generation using DiceBear API
- **Demo-Specific Enums**: New `DEMO` role and family values for proper categorization
- **Branded Demo Email**: Clean …
=> feat(ui): Implement personalized sidebar with real user data and enhanced UX

next.config.ts, src/middleware.ts
This PR builds on previous Lighthouse improvements with advanced bundle optimization techniques and enhanced CSP compatibility for Turnstile.
- **Unused JavaScript**: Aggressive tree-shaking for UI component libraries
- **Legacy Polyfills**: Better code splitting to reduce unnecessary transforms
- **Icon Loading**: Modular imports for lucide-react to load only used icons
- **CSP Compatibility**: Enhanced security headers for Turnstile functionality
- **Expanded `optimizePackageImports`**: All Radix UI components now benefit from tree-shaking
- `@radix-ui/react-dialog`, `@radix-ui/react-select`, `@radix-ui/react-tooltip`
- `@radix-ui/react-separator`, `@radix-ui/react-label`, `@radix-ui/react-checkbox`
- `@radix-ui/react-collapsible`, `@radix-ui/react-alert-dialog`, `@radix-ui/react-slot` …
=> perf: Enhanced bundle optimization and Turnstile CSP compatibility

src/app/layout.tsx, src/app/manifest.ts, src/components/dynamic-theme-color.tsx
This PR introduces a dynamic theme color system that automatically updates the browser's theme color meta tag based on the user's current theme preference, along with a fix to ensure the dark mode theme color properly matches the application's dark background.
- **Added `DynamicThemeColor` component**: A new client-side component that dynamically manages the `theme-color` meta tag
- **Integrated theme color management**: The component is now included in the root layout to provide app-wide theme color updates
- **Fixed dark mode color matching**: Adjusted the dark mode theme color to properly align with the actual dark mode background color defined in `globals.css`
- The `DynamicThemeColor` component listens for theme changes and updates the browser's theme color accordingly
- Removes …
=> feat: Implement dynamic theme color system with proper dark mode support
